### ISSUE TITLE
Home Inventory

### ISSUE THREAD

**Issue by andrej1919** [dgwyer/fasthtml-demos#1]
Hi,

I have a SQLite database for home inventory ([inventory.txt](https://github.com/user-attachments/files/16974596/inventory.txt)) and I would like to be able to enter, update and delete data using FastHTML. The idea is to use forms, drop-downs  etc. for data entry.  Search function would be highly appreciated as well. Please advise whether this is possible.

Thanks,
Andrej

**Comment by dgwyer** [comment]
Hi Andrej,

Yes, that's definitely doable. The official FastHTML examples contains a few examples of how to read/write to an SQLite db.

https://github.com/AnswerDotAI/fasthtml-example

**Comment by andrej1919** [comment]
Hi David,

I checked those examples before I contacted you (got your contact while browsing Discord thread), but my conclusion is that those examples are too simplistic. I am fluent in SQL, beginner in Python and I will have a hard time to do it myself if at all possible. As a matter of fact, I am willing to hire someone. Please advise if you are interested or if you know someone that would do it.

**Comment by dgwyer** [comment]
@andrej1919 Are you on the fast.ai Discord server? This is where the main FastHTML channel is. I'm on there. Feel free to DM me. My u/n is @dgwyer.

Fast.ai Discord invite link: https://discord.com/invite/xnpeRdg
